'''
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
DO NOT EDIT THIS FILE
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
'''

import io
from unittest import mock, TestCase

from baking import print_ingredients, confirm_ingredients, favorite_bake


class TestBakingStrings(TestCase):

    @mock.patch('sys.stdout', new_callable=io.StringIO)
    def test_print_ingredients(self, mock_stdout):
        print_ingredients()

        self.assertEqual(
            'milk eggs flour sugar\nmilk eggs flour sugar\nmilk eggs flour sugar\n',
            mock_stdout.getvalue()
        )

    @mock.patch('sys.stdout', new_callable=io.StringIO)
    def test_confirm_ingredients(self, mock_stdout):
        confirm_ingredients()

        self.assertEqual(
            'butter eggs flour sugar\n1\nmilk eggs flour sugar\nbutter eggs flour sugar\nBUTTER EGGS FLOUR SUGAR\n',
            mock_stdout.getvalue()
        )

    @mock.patch('builtins.input', side_effect=['brownie', '4'])
    @mock.patch('sys.stdout', new_callable=io.StringIO)
    def test_favorite_bake(self, mock_stdout, mock_input):
        favorite_bake()

        # Since we are patching the input() function, those printouts don't appear
        self.assertEqual(
            "<class 'str'>\nOoooh, brownies are delicious!\nWe recommend you eat brownies at least 8 times a month!\n",
            mock_stdout.getvalue()
        )
